[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "scrapy-feedexporter-azure-storage"
version = "0.1.0"
description = "Scrapy Feed Exporter for Azure Storage"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{ name = "Zyte", email = "opensource@zyte.com" }]
dependencies = [
    "azure-storage-blob",
    "scrapy",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Scrapy",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/scrapy-plugins/scrapy-feedexporter-azure-storage"
Source = "https://github.com/scrapy-plugins/scrapy-feedexporter-azure-storage"
Issues = "https://github.com/scrapy-plugins/scrapy-feedexporter-azure-storage/issues"

[tool.hatch.build.targets.wheel]
packages = ["scrapy_azure_exporter"]

[tool.hatch.build.targets.sdist]
include = [
    "/scrapy_azure_exporter",
    "/tests",
    "/README.md",
    "/CHANGES.rst",
    "/LICENSE",
]

[tool.bumpversion]
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = "CHANGES.rst"
search = '{current_version} (unreleased)'
replace = '{current_version} ({now:%Y-%m-%d})'
